paths:
  project_folder: "/nobackup/rossby27/users/sm_erhol/station_attribution_article/summer2018"
  data:
    gridclim: "/nobackup/smhid17/proj/sik/SMHIGridClim_NORDIC-11/v0.9/netcdf/day/"
    eobs: "/home/rossby/imports/obs/EOBS/EOBS24-0e/EUR-10/remap/EUR-11/day/"
    era5: "/home/rossby/imports/obs/ECMWF/ERA5/remap/EUR-11/day/"
    cordex: "/nobackup/rossby21/sm_renwi/DATA/MidasOut/"
    s-lens: "/nobackup/rossby22/rossby/joint_exp/large_ensemble/cmorized/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/"

  shapefile: "/home/sm_erhol/data/ne_10_admin_0_countries/ne_10m_admin_0_countries.shp"

project_name: "summer2018"
filenames:
  gridclim: "SMHIGridClim_day"
  eobs: "EOBS_day"
  era5: "era5_day"
  cordex: "CORDEX-ENS_rcp85_day"
  s-lens: "s-lens_day"

epsg: 3006

variable:
  - "tasmax"
  - "tasmin"

index_name:
  - "txge25"
  - "ctxge25"


partial_dates:
  low:
    year: 1989
  high:
    year: 2018
    month: 12
    day: 31

season: False

roi_extent:
  north: 60.0
  south: 55.0
  east: 19.5
  west: 11.2

